### ISSUE TITLE
Error in soil_fac

### ISSUE THREAD

**Issue by KerryLM** [michstrauch/TopHRU#5]
Hello, I ran through the available tutorial successfully but am running into an issue when trying to analyze my own data:

Error in soil_fac[cbind(SOIL, SUBBASIN, LANDUSE, which(soil_seq == thrs_comb[j,  : 
  subscript out of bounds

I believe I have my .csv formatted correctly per the instructions so I am wondering if it is an issue with the code or perhaps software related? Any guidance appreciated.

Kerry

**Comment by michstrauch** [comment]
Hi Kerry,
thanks for raising this issue. The problem is caused by your soil names, which consist only of numbers. Make sure there is atleast one character in your soil names. Only then, TopHRU will treat the soil names as factors and run succesfully!
Best,
Michael
